# MySQL.  Versions 4.1 and 5.0 are recommended.
#
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: soucarioca_dev
  pool: 5
  username: root
  password: 123456
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: soucarioca_test
  pool: 5
  username: root
  password: 123456
  host: localhost


production:
  adapter:
  encoding:
  reconnect:
  database:
  pool: 5
  username:
  password:
  host:
  port: 
